/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncomeIndexRouteImport } from './routes/income/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as IncomeAddRouteImport } from './routes/income/add'
import { Route as AccountsAddRouteImport } from './routes/accounts/add'
import { Route as IncomeIncomeIdEditRouteImport } from './routes/income/$incomeId.edit'
import { Route as AccountsAccountIdEditRouteImport } from './routes/accounts/$accountId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeIndexRoute = IncomeIndexRouteImport.update({
  id: '/income/',
  path: '/income/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeAddRoute = IncomeAddRouteImport.update({
  id: '/income/add',
  path: '/income/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAddRoute = AccountsAddRouteImport.update({
  id: '/accounts/add',
  path: '/accounts/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeIncomeIdEditRoute = IncomeIncomeIdEditRouteImport.update({
  id: '/income/$incomeId/edit',
  path: '/income/$incomeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdEditRoute = AccountsAccountIdEditRouteImport.update({
  id: '/accounts/$accountId/edit',
  path: '/accounts/$accountId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts/add': typeof AccountsAddRoute
  '/income/add': typeof IncomeAddRoute
  '/accounts': typeof AccountsIndexRoute
  '/income': typeof IncomeIndexRoute
  '/accounts/$accountId/edit': typeof AccountsAccountIdEditRoute
  '/income/$incomeId/edit': typeof IncomeIncomeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts/add': typeof AccountsAddRoute
  '/income/add': typeof IncomeAddRoute
  '/accounts': typeof AccountsIndexRoute
  '/income': typeof IncomeIndexRoute
  '/accounts/$accountId/edit': typeof AccountsAccountIdEditRoute
  '/income/$incomeId/edit': typeof IncomeIncomeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts/add': typeof AccountsAddRoute
  '/income/add': typeof IncomeAddRoute
  '/accounts/': typeof AccountsIndexRoute
  '/income/': typeof IncomeIndexRoute
  '/accounts/$accountId/edit': typeof AccountsAccountIdEditRoute
  '/income/$incomeId/edit': typeof IncomeIncomeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts/add'
    | '/income/add'
    | '/accounts'
    | '/income'
    | '/accounts/$accountId/edit'
    | '/income/$incomeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts/add'
    | '/income/add'
    | '/accounts'
    | '/income'
    | '/accounts/$accountId/edit'
    | '/income/$incomeId/edit'
  id:
    | '__root__'
    | '/'
    | '/accounts/add'
    | '/income/add'
    | '/accounts/'
    | '/income/'
    | '/accounts/$accountId/edit'
    | '/income/$incomeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsAddRoute: typeof AccountsAddRoute
  IncomeAddRoute: typeof IncomeAddRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  IncomeIndexRoute: typeof IncomeIndexRoute
  AccountsAccountIdEditRoute: typeof AccountsAccountIdEditRoute
  IncomeIncomeIdEditRoute: typeof IncomeIncomeIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income/': {
      id: '/income/'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income/add': {
      id: '/income/add'
      path: '/income/add'
      fullPath: '/income/add'
      preLoaderRoute: typeof IncomeAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/add': {
      id: '/accounts/add'
      path: '/accounts/add'
      fullPath: '/accounts/add'
      preLoaderRoute: typeof AccountsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income/$incomeId/edit': {
      id: '/income/$incomeId/edit'
      path: '/income/$incomeId/edit'
      fullPath: '/income/$incomeId/edit'
      preLoaderRoute: typeof IncomeIncomeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId/edit': {
      id: '/accounts/$accountId/edit'
      path: '/accounts/$accountId/edit'
      fullPath: '/accounts/$accountId/edit'
      preLoaderRoute: typeof AccountsAccountIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsAddRoute: AccountsAddRoute,
  IncomeAddRoute: IncomeAddRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  IncomeIndexRoute: IncomeIndexRoute,
  AccountsAccountIdEditRoute: AccountsAccountIdEditRoute,
  IncomeIncomeIdEditRoute: IncomeIncomeIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
