/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinancialItemsSavingsIndexRouteImport } from './routes/financial-items/savings/index'
import { Route as FinancialItemsMortgageIndexRouteImport } from './routes/financial-items/mortgage/index'
import { Route as FinancialItemsIncomeIndexRouteImport } from './routes/financial-items/income/index'
import { Route as FinancialItemsExpensesIndexRouteImport } from './routes/financial-items/expenses/index'
import { Route as FinancialItemsCheckingIndexRouteImport } from './routes/financial-items/checking/index'
import { Route as FinancialItemsSavingsAddRouteImport } from './routes/financial-items/savings/add'
import { Route as FinancialItemsMortgageAddRouteImport } from './routes/financial-items/mortgage/add'
import { Route as FinancialItemsIncomeAddRouteImport } from './routes/financial-items/income/add'
import { Route as FinancialItemsExpensesAddRouteImport } from './routes/financial-items/expenses/add'
import { Route as FinancialItemsCheckingAddRouteImport } from './routes/financial-items/checking/add'
import { Route as FinancialItemsSavingsIdEditRouteImport } from './routes/financial-items/savings/$id.edit'
import { Route as FinancialItemsMortgageIdEditRouteImport } from './routes/financial-items/mortgage/$id.edit'
import { Route as FinancialItemsIncomeIdEditRouteImport } from './routes/financial-items/income/$id.edit'
import { Route as FinancialItemsExpensesIdEditRouteImport } from './routes/financial-items/expenses/$id.edit'
import { Route as FinancialItemsCheckingIdEditRouteImport } from './routes/financial-items/checking/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialItemsSavingsIndexRoute =
  FinancialItemsSavingsIndexRouteImport.update({
    id: '/financial-items/savings/',
    path: '/financial-items/savings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsMortgageIndexRoute =
  FinancialItemsMortgageIndexRouteImport.update({
    id: '/financial-items/mortgage/',
    path: '/financial-items/mortgage/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsIncomeIndexRoute =
  FinancialItemsIncomeIndexRouteImport.update({
    id: '/financial-items/income/',
    path: '/financial-items/income/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsExpensesIndexRoute =
  FinancialItemsExpensesIndexRouteImport.update({
    id: '/financial-items/expenses/',
    path: '/financial-items/expenses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsCheckingIndexRoute =
  FinancialItemsCheckingIndexRouteImport.update({
    id: '/financial-items/checking/',
    path: '/financial-items/checking/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsSavingsAddRoute =
  FinancialItemsSavingsAddRouteImport.update({
    id: '/financial-items/savings/add',
    path: '/financial-items/savings/add',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsMortgageAddRoute =
  FinancialItemsMortgageAddRouteImport.update({
    id: '/financial-items/mortgage/add',
    path: '/financial-items/mortgage/add',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsIncomeAddRoute = FinancialItemsIncomeAddRouteImport.update({
  id: '/financial-items/income/add',
  path: '/financial-items/income/add',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialItemsExpensesAddRoute =
  FinancialItemsExpensesAddRouteImport.update({
    id: '/financial-items/expenses/add',
    path: '/financial-items/expenses/add',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsCheckingAddRoute =
  FinancialItemsCheckingAddRouteImport.update({
    id: '/financial-items/checking/add',
    path: '/financial-items/checking/add',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsSavingsIdEditRoute =
  FinancialItemsSavingsIdEditRouteImport.update({
    id: '/financial-items/savings/$id/edit',
    path: '/financial-items/savings/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsMortgageIdEditRoute =
  FinancialItemsMortgageIdEditRouteImport.update({
    id: '/financial-items/mortgage/$id/edit',
    path: '/financial-items/mortgage/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsIncomeIdEditRoute =
  FinancialItemsIncomeIdEditRouteImport.update({
    id: '/financial-items/income/$id/edit',
    path: '/financial-items/income/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsExpensesIdEditRoute =
  FinancialItemsExpensesIdEditRouteImport.update({
    id: '/financial-items/expenses/$id/edit',
    path: '/financial-items/expenses/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancialItemsCheckingIdEditRoute =
  FinancialItemsCheckingIdEditRouteImport.update({
    id: '/financial-items/checking/$id/edit',
    path: '/financial-items/checking/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/financial-items/checking/add': typeof FinancialItemsCheckingAddRoute
  '/financial-items/expenses/add': typeof FinancialItemsExpensesAddRoute
  '/financial-items/income/add': typeof FinancialItemsIncomeAddRoute
  '/financial-items/mortgage/add': typeof FinancialItemsMortgageAddRoute
  '/financial-items/savings/add': typeof FinancialItemsSavingsAddRoute
  '/financial-items/checking': typeof FinancialItemsCheckingIndexRoute
  '/financial-items/expenses': typeof FinancialItemsExpensesIndexRoute
  '/financial-items/income': typeof FinancialItemsIncomeIndexRoute
  '/financial-items/mortgage': typeof FinancialItemsMortgageIndexRoute
  '/financial-items/savings': typeof FinancialItemsSavingsIndexRoute
  '/financial-items/checking/$id/edit': typeof FinancialItemsCheckingIdEditRoute
  '/financial-items/expenses/$id/edit': typeof FinancialItemsExpensesIdEditRoute
  '/financial-items/income/$id/edit': typeof FinancialItemsIncomeIdEditRoute
  '/financial-items/mortgage/$id/edit': typeof FinancialItemsMortgageIdEditRoute
  '/financial-items/savings/$id/edit': typeof FinancialItemsSavingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/financial-items/checking/add': typeof FinancialItemsCheckingAddRoute
  '/financial-items/expenses/add': typeof FinancialItemsExpensesAddRoute
  '/financial-items/income/add': typeof FinancialItemsIncomeAddRoute
  '/financial-items/mortgage/add': typeof FinancialItemsMortgageAddRoute
  '/financial-items/savings/add': typeof FinancialItemsSavingsAddRoute
  '/financial-items/checking': typeof FinancialItemsCheckingIndexRoute
  '/financial-items/expenses': typeof FinancialItemsExpensesIndexRoute
  '/financial-items/income': typeof FinancialItemsIncomeIndexRoute
  '/financial-items/mortgage': typeof FinancialItemsMortgageIndexRoute
  '/financial-items/savings': typeof FinancialItemsSavingsIndexRoute
  '/financial-items/checking/$id/edit': typeof FinancialItemsCheckingIdEditRoute
  '/financial-items/expenses/$id/edit': typeof FinancialItemsExpensesIdEditRoute
  '/financial-items/income/$id/edit': typeof FinancialItemsIncomeIdEditRoute
  '/financial-items/mortgage/$id/edit': typeof FinancialItemsMortgageIdEditRoute
  '/financial-items/savings/$id/edit': typeof FinancialItemsSavingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/financial-items/checking/add': typeof FinancialItemsCheckingAddRoute
  '/financial-items/expenses/add': typeof FinancialItemsExpensesAddRoute
  '/financial-items/income/add': typeof FinancialItemsIncomeAddRoute
  '/financial-items/mortgage/add': typeof FinancialItemsMortgageAddRoute
  '/financial-items/savings/add': typeof FinancialItemsSavingsAddRoute
  '/financial-items/checking/': typeof FinancialItemsCheckingIndexRoute
  '/financial-items/expenses/': typeof FinancialItemsExpensesIndexRoute
  '/financial-items/income/': typeof FinancialItemsIncomeIndexRoute
  '/financial-items/mortgage/': typeof FinancialItemsMortgageIndexRoute
  '/financial-items/savings/': typeof FinancialItemsSavingsIndexRoute
  '/financial-items/checking/$id/edit': typeof FinancialItemsCheckingIdEditRoute
  '/financial-items/expenses/$id/edit': typeof FinancialItemsExpensesIdEditRoute
  '/financial-items/income/$id/edit': typeof FinancialItemsIncomeIdEditRoute
  '/financial-items/mortgage/$id/edit': typeof FinancialItemsMortgageIdEditRoute
  '/financial-items/savings/$id/edit': typeof FinancialItemsSavingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/financial-items/checking/add'
    | '/financial-items/expenses/add'
    | '/financial-items/income/add'
    | '/financial-items/mortgage/add'
    | '/financial-items/savings/add'
    | '/financial-items/checking'
    | '/financial-items/expenses'
    | '/financial-items/income'
    | '/financial-items/mortgage'
    | '/financial-items/savings'
    | '/financial-items/checking/$id/edit'
    | '/financial-items/expenses/$id/edit'
    | '/financial-items/income/$id/edit'
    | '/financial-items/mortgage/$id/edit'
    | '/financial-items/savings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/financial-items/checking/add'
    | '/financial-items/expenses/add'
    | '/financial-items/income/add'
    | '/financial-items/mortgage/add'
    | '/financial-items/savings/add'
    | '/financial-items/checking'
    | '/financial-items/expenses'
    | '/financial-items/income'
    | '/financial-items/mortgage'
    | '/financial-items/savings'
    | '/financial-items/checking/$id/edit'
    | '/financial-items/expenses/$id/edit'
    | '/financial-items/income/$id/edit'
    | '/financial-items/mortgage/$id/edit'
    | '/financial-items/savings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/financial-items/checking/add'
    | '/financial-items/expenses/add'
    | '/financial-items/income/add'
    | '/financial-items/mortgage/add'
    | '/financial-items/savings/add'
    | '/financial-items/checking/'
    | '/financial-items/expenses/'
    | '/financial-items/income/'
    | '/financial-items/mortgage/'
    | '/financial-items/savings/'
    | '/financial-items/checking/$id/edit'
    | '/financial-items/expenses/$id/edit'
    | '/financial-items/income/$id/edit'
    | '/financial-items/mortgage/$id/edit'
    | '/financial-items/savings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinancialItemsCheckingAddRoute: typeof FinancialItemsCheckingAddRoute
  FinancialItemsExpensesAddRoute: typeof FinancialItemsExpensesAddRoute
  FinancialItemsIncomeAddRoute: typeof FinancialItemsIncomeAddRoute
  FinancialItemsMortgageAddRoute: typeof FinancialItemsMortgageAddRoute
  FinancialItemsSavingsAddRoute: typeof FinancialItemsSavingsAddRoute
  FinancialItemsCheckingIndexRoute: typeof FinancialItemsCheckingIndexRoute
  FinancialItemsExpensesIndexRoute: typeof FinancialItemsExpensesIndexRoute
  FinancialItemsIncomeIndexRoute: typeof FinancialItemsIncomeIndexRoute
  FinancialItemsMortgageIndexRoute: typeof FinancialItemsMortgageIndexRoute
  FinancialItemsSavingsIndexRoute: typeof FinancialItemsSavingsIndexRoute
  FinancialItemsCheckingIdEditRoute: typeof FinancialItemsCheckingIdEditRoute
  FinancialItemsExpensesIdEditRoute: typeof FinancialItemsExpensesIdEditRoute
  FinancialItemsIncomeIdEditRoute: typeof FinancialItemsIncomeIdEditRoute
  FinancialItemsMortgageIdEditRoute: typeof FinancialItemsMortgageIdEditRoute
  FinancialItemsSavingsIdEditRoute: typeof FinancialItemsSavingsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/savings/': {
      id: '/financial-items/savings/'
      path: '/financial-items/savings'
      fullPath: '/financial-items/savings'
      preLoaderRoute: typeof FinancialItemsSavingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/mortgage/': {
      id: '/financial-items/mortgage/'
      path: '/financial-items/mortgage'
      fullPath: '/financial-items/mortgage'
      preLoaderRoute: typeof FinancialItemsMortgageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/income/': {
      id: '/financial-items/income/'
      path: '/financial-items/income'
      fullPath: '/financial-items/income'
      preLoaderRoute: typeof FinancialItemsIncomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/expenses/': {
      id: '/financial-items/expenses/'
      path: '/financial-items/expenses'
      fullPath: '/financial-items/expenses'
      preLoaderRoute: typeof FinancialItemsExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/checking/': {
      id: '/financial-items/checking/'
      path: '/financial-items/checking'
      fullPath: '/financial-items/checking'
      preLoaderRoute: typeof FinancialItemsCheckingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/savings/add': {
      id: '/financial-items/savings/add'
      path: '/financial-items/savings/add'
      fullPath: '/financial-items/savings/add'
      preLoaderRoute: typeof FinancialItemsSavingsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/mortgage/add': {
      id: '/financial-items/mortgage/add'
      path: '/financial-items/mortgage/add'
      fullPath: '/financial-items/mortgage/add'
      preLoaderRoute: typeof FinancialItemsMortgageAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/income/add': {
      id: '/financial-items/income/add'
      path: '/financial-items/income/add'
      fullPath: '/financial-items/income/add'
      preLoaderRoute: typeof FinancialItemsIncomeAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/expenses/add': {
      id: '/financial-items/expenses/add'
      path: '/financial-items/expenses/add'
      fullPath: '/financial-items/expenses/add'
      preLoaderRoute: typeof FinancialItemsExpensesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/checking/add': {
      id: '/financial-items/checking/add'
      path: '/financial-items/checking/add'
      fullPath: '/financial-items/checking/add'
      preLoaderRoute: typeof FinancialItemsCheckingAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/savings/$id/edit': {
      id: '/financial-items/savings/$id/edit'
      path: '/financial-items/savings/$id/edit'
      fullPath: '/financial-items/savings/$id/edit'
      preLoaderRoute: typeof FinancialItemsSavingsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/mortgage/$id/edit': {
      id: '/financial-items/mortgage/$id/edit'
      path: '/financial-items/mortgage/$id/edit'
      fullPath: '/financial-items/mortgage/$id/edit'
      preLoaderRoute: typeof FinancialItemsMortgageIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/income/$id/edit': {
      id: '/financial-items/income/$id/edit'
      path: '/financial-items/income/$id/edit'
      fullPath: '/financial-items/income/$id/edit'
      preLoaderRoute: typeof FinancialItemsIncomeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/expenses/$id/edit': {
      id: '/financial-items/expenses/$id/edit'
      path: '/financial-items/expenses/$id/edit'
      fullPath: '/financial-items/expenses/$id/edit'
      preLoaderRoute: typeof FinancialItemsExpensesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-items/checking/$id/edit': {
      id: '/financial-items/checking/$id/edit'
      path: '/financial-items/checking/$id/edit'
      fullPath: '/financial-items/checking/$id/edit'
      preLoaderRoute: typeof FinancialItemsCheckingIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinancialItemsCheckingAddRoute: FinancialItemsCheckingAddRoute,
  FinancialItemsExpensesAddRoute: FinancialItemsExpensesAddRoute,
  FinancialItemsIncomeAddRoute: FinancialItemsIncomeAddRoute,
  FinancialItemsMortgageAddRoute: FinancialItemsMortgageAddRoute,
  FinancialItemsSavingsAddRoute: FinancialItemsSavingsAddRoute,
  FinancialItemsCheckingIndexRoute: FinancialItemsCheckingIndexRoute,
  FinancialItemsExpensesIndexRoute: FinancialItemsExpensesIndexRoute,
  FinancialItemsIncomeIndexRoute: FinancialItemsIncomeIndexRoute,
  FinancialItemsMortgageIndexRoute: FinancialItemsMortgageIndexRoute,
  FinancialItemsSavingsIndexRoute: FinancialItemsSavingsIndexRoute,
  FinancialItemsCheckingIdEditRoute: FinancialItemsCheckingIdEditRoute,
  FinancialItemsExpensesIdEditRoute: FinancialItemsExpensesIdEditRoute,
  FinancialItemsIncomeIdEditRoute: FinancialItemsIncomeIdEditRoute,
  FinancialItemsMortgageIdEditRoute: FinancialItemsMortgageIdEditRoute,
  FinancialItemsSavingsIdEditRoute: FinancialItemsSavingsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
